# Edit this file to add dependencies to environment,
# Then run `./lock-environment.sh` to generate reproducible lock files

# !!! If you are developing the website locally use the existing lock files
# for your platform (`conda create --name hackweek --file conda-osx-64.lock`)
name: hackweek
channels:
  - conda-forge
dependencies:
  - cookiecutter
  - git
  - ipyleaflet
  - jinja2>=2.11
  - jupyter-book=0.12
  - jupyter-resource-usage
  - jupyterhub-singleuser
  - jupyterlab=3
  - pip
  - pygments>=2.6.1
  - pymdown-extensions>=7.1
  - python=3.10
  - sphinxcontrib-bibtex
  - vim
  - wget
  - pip:
    - jinja-markdown==1.210911
platforms:
  - linux-64
  - osx-64
