# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: ICESat-2 Hackweek 2024
author: eScience Institute, University of Washington
logo: logo.png
only_build_toc_files: true

parse:
  # https://jupyterbook.org/content/content-blocks.html?highlight=myst%20substitution#define-substitutions-for-your-whole-book
  # https://jupyterbook.org/content/content-blocks.html#using-substitutions-in-links
  myst_substitutions:
    hackweek: "ICESat-2 Hackweek"
    dates: "Aug 19-23, 2024"
    github_org_url: "https://github.com/ICESAT-2HackWeek"
    book_repo: "website-2024"
    website_url: "https://icesat-2.hackweek.io"
    jupyterhub_url: "https://hub.cryointhecloud.com/"
    slack_workspace_url: "https://2024-uw-hackweek.slack.com"
    contact_email: "escience-hackweeks@uw.edu"
    dataset: "INSERT_DATA_SET_NAME"
    anon_reporting_url: "https://bit.ly/uwhackweekfeedback"
    project_spreadsheet_url: "https://INSERT_GOOGLE_SHEET"
  myst_enable_extensions:
    # Defaults
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    # Extras
    - html_image

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  # NOTE: 'cache' to use jupyter-cache, or 'force' to run all
  execute_notebooks: 'force'
  exclude_patterns:
    - "**/geospatial-advanced.ipynb"
    - "cloud-computing/04-cloud-optimized-icesat2.ipynb"
    - "cloud-computing/atl08_parquet_files/atl08_parquet.ipynb"
    - "machine-learning/point_cloud_classifier.ipynb"
    - "**/ICESat2_Data_Access_Tutorial.ipynb"
  allow_errors: false
  # Per-cell notebook execution limit (seconds)
  timeout: 300

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Configure your Binder links, such as the URL of the BinderHub.
launch_buttons:
  notebook_interface: jupyterlab
  jupyterhub_url: "https://hub.cryointhecloud.com/"

# Information about where the book exists on the web
repository:
  url: https://github.com/ICESAT-2HackWeek/website-2024 # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Bibliography
bibtex_bibfiles:
  - references.bib
sphinx:
  config:
    suppress_warnings: ["mystnb.unknown_mime_type", "myst.header"]
    bibtex_reference_style: author_year  # or label, super, \supercite
    nb_custom_formats:
        .py:
            - jupytext.reads
            - fmt: py:percent
  local_extensions:
    build_gallery: "_ext"

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  # google_analytics_id: G-XXXXXXXXX
