name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-example-book:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if environment.yaml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yaml') }}
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: false
        use-only-tar-bz2: true
        miniconda-version: 'latest'
        python-version: 3.8
        environment-file: environment.yml
        activate-environment: hackweek

    - name: Build book
      shell: bash -l {0}
      run: |
        jupyter-book build book/

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAT }}
        publish_dir: book/_build/html
        publish_branch: gh-pages
