name: Test

on:
  pull_request:
    paths:
      - 'book/**'
      - '.github/workflows/test.yaml'
    branches:
      - main

env:
  DOCKER_IMAGE: uwhackweek/template:latest

jobs:
  quality-control:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    # NOTE: this isn't a comprehensive spellcheck, just common typos
    - name: Spellcheck
      uses: codespell-project/actions-codespell@master
      with:
        check_filenames: true
        check_hidden: true
        only_warn: true

    - name: Ensure clean notebooks
      run: |
        pip install nb-clean
        find book -name "*ipynb" | xargs nb-clean check


  build-and-test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Pull Docker Image
      run: |
        docker pull $DOCKER_IMAGE
        docker images

    - name: Build JupyterBook
      run: |
        docker run -u root -v ${{ github.workspace }}:/home/jovyan:rw $DOCKER_IMAGE jb build book --warningiserror --keep-going

    - name: Check External Links
      run: |
        docker run -u root -v ${{ github.workspace }}:/home/jovyan:rw $DOCKER_IMAGE jb build book --builder linkcheck

    - name: Save Build
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: book/_build/
