name: Test

on:
  pull_request_target:
    types: [labeled, synchronize]
    paths:
      - 'book/**'
      - '.github/workflows/test.yaml'
      - '{{ cookiecutter.repo_directory }}/**'
      - 'scripts/**'
      - 'binder/**'
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: ./.github/actions/buildbook
      with:
        jb-cache: true
        publish-to-gh: false
        jb-save: true
